import matplotlib.pyplot as plt
import cv2
from skimage import data

img=data.moon()
equalized_img = cv2.equalizeHist(img)
clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
clahe_img = clahe.apply(img)
blur = cv2.blur(img, (5, 5))  
gaussianblur = cv2.GaussianBlur(img, (5, 5), 0)
median = cv2.medianBlur(img, 5)
edges = cv2.Canny(img, 20, 40)
p1 = clahe.apply(cv2.GaussianBlur(img, (5, 5), 0))
p2 = cv2.GaussianBlur(clahe.apply(img), (5, 5), 0)

fig1, axes = plt.subplots(2, 3, figsize=(8, 10))
axes[0][0].imshow(img, cmap='gray', vmin=0, vmax=255)
axes[0][0].set_title('Original Image')
axes[0][0].axis('off')

axes[0][1].imshow(equalized_img, cmap='gray', vmin=0, vmax=255)
axes[0][1].set_title('Equalized Image')
axes[0][1].axis('off')

axes[0][2].imshow(clahe_img, cmap='gray', vmin=0, vmax=255)
axes[0][2].set_title('CLAHE Image')
axes[0][2].axis('off')

axes[1][0].hist(img.ravel(), bins=256, range=(0, 255), color='blue', density=True)
axes[1][0].set_title('Original Image Histogram')
axes[1][0].set_xlim([0, 255])
axes[1][0].set_ylabel('Probability')

axes[1][1].hist(equalized_img.ravel(), bins=256, range=(0, 255), color='green', density=True)
axes[1][1].set_title('Equalized Image Histogram')
axes[1][1].set_xlim([0, 255])
axes[1][1].set_ylabel('Probability')

axes[1][2].hist(clahe_img.ravel(), bins=256, range=(0, 255), color='red', density=True)
axes[1][2].set_title('CLAHE Image Histogram')
axes[1][2].set_xlim([0, 255])
axes[1][2].set_ylabel('Probability')

fig2, axes = plt.subplots(2, 3, figsize=(8, 10))
axes[0][0].imshow(blur, cmap='gray', vmin=0, vmax=255)
axes[0][0].set_title('Blurred Image')
axes[0][0].axis('off')

axes[0][1].imshow(gaussianblur, cmap='gray', vmin=0, vmax=255)
axes[0][1].set_title('Gaussian Blurred Image')
axes[0][1].axis('off')

axes[0][2].imshow(median, cmap='gray', vmin=0, vmax=255)
axes[0][2].set_title('Median Blurred Image')
axes[0][2].axis('off')

axes[1][0].hist(blur.ravel(), bins=256, range=(0, 255), color='cyan', density=True)
axes[1][0].set_title('Blurred Image Histogram')
axes[1][0].set_xlim([0, 255])
axes[1][0].set_ylabel('Probability')    

axes[1][1].hist(gaussianblur.ravel(), bins=256, range=(0, 255), color='magenta', density=True)
axes[1][1].set_title('Gaussian Blurred Image Histogram')
axes[1][1].set_xlim([0, 255])
axes[1][1].set_ylabel('Probability')

axes[1][2].hist(median.ravel(), bins=256, range=(0, 255), color='yellow', density=True)
axes[1][2].set_title('Median Blurred Image Histogram')  
axes[1][2].set_xlim([0, 255])
axes[1][2].set_ylabel('Probability')

fig3, axes = plt.subplots(2, 3, figsize=(8, 10))
axes[0][0].imshow(edges, cmap='gray', vmin=0, vmax=255)
axes[0][0].set_title('Canny Edges')
axes[0][0].axis('off')

axes[0][1].imshow(p1, cmap='gray', vmin=0, vmax=255)
axes[0][1].set_title('CLAHE + GaussianBlur')    
axes[0][1].axis('off')

axes[0][2].imshow(p2, cmap='gray', vmin=0, vmax=255)
axes[0][2].set_title('GaussianBlur + CLAHE')    
axes[0][2].axis('off')

axes[1][0].hist(edges.ravel(), bins=256, range=(0, 255), color='orange', density=True)
axes[1][0].set_title('Canny Edges Histogram')   
axes[1][0].set_xlim([0, 255])
axes[1][0].set_ylabel('Probability')

axes[1][1].hist(p1.ravel(), bins=256, range=(0, 255), color='purple', density=True)
axes[1][1].set_title('CLAHE + GaussianBlur Histogram')
axes[1][1].set_xlim([0, 255])
axes[1][1].set_ylabel('Probability')

axes[1][2].hist(p2.ravel(), bins=256, range=(0, 255), color='brown', density=True)
axes[1][2].set_title('GaussianBlur + CLAHE Histogram')  
axes[1][2].set_xlim([0, 255])
axes[1][2].set_ylabel('Probability')

plt.tight_layout()
plt.show()
fig1.savefig('/home/ptz/cv-course/theory/week02/fig1.jpg')
fig2.savefig('/home/ptz/cv-course/theory/week02/fig2.jpg')
fig3.savefig('/home/ptz/cv-course/theory/week02/fig3.jpg')

mse1 = ((img - equalized_img) ** 2).mean()
mse2 = ((img - clahe_img) ** 2).mean()
mse3 = ((img - blur) ** 2).mean()
mse4 = ((img - gaussianblur) ** 2).mean()
mse5 = ((img - median) ** 2).mean()
mse6 = ((img - edges) ** 2).mean()
mse7 = ((img - p1) ** 2).mean()
mse8 = ((img - p2) ** 2).mean()
psnr1 = cv2.PSNR(img, equalized_img)
psnr2 = cv2.PSNR(img, clahe_img)
psnr3 = cv2.PSNR(img, blur)
psnr4 = cv2.PSNR(img, gaussianblur)
psnr5 = cv2.PSNR(img, median)
psnr6 = cv2.PSNR(img, edges)
psnr7 = cv2.PSNR(img, p1)
psnr8 = cv2.PSNR(img, p2)
print(f"Equalized Image: MSE = {mse1:.4f}, PSNR = {psnr1:.4f} dB")
print(f"CLAHE Image: MSE = {mse2:.4f}, PSNR = {psnr2:.4f} dB")
print(f"Blurred Image: MSE = {mse3:.4f}, PSNR = {psnr3:.4f} dB")
print(f"Gaussian Blurred Image: MSE = {mse4:.4f}, PSNR = {psnr4:.4f} dB")
print(f"Median Blurred Image: MSE = {mse5:.4f}, PSNR = {psnr5:.4f} dB")
print(f"Canny Edges: MSE = {mse6:.4f}, PSNR = {psnr6:.4f} dB")
print(f"CLAHE + GaussianBlur: MSE = {mse7:.4f}, PSNR = {psnr7:.4f} dB")
print(f"GaussianBlur + CLAHE: MSE = {mse8:.4f}, PSNR = {psnr8:.4f} dB")